package smd
package parsing

import scala.{Product, Product4}

// THIS FILE IS AUTOMATICALLY GENERATED
// Generated at: 2013-09-01T23:01:53Z

/** Parses 4 expressions, providing strongly-typed results.
  * 
  * @param  _1  the 1th parser in the sequence.
  * @tparam T1  the product type of the 1th parser in the sequence.
  * @param  _2  the 2th parser in the sequence.
  * @tparam T2  the product type of the 2th parser in the sequence.
  * @param  _3  the 3th parser in the sequence.
  * @tparam T3  the product type of the 3th parser in the sequence.
  * @param  _4  the 4th parser in the sequence.
  * @tparam T4  the product type of the 4th parser in the sequence.
  */
case class SequenceParser4[+T1, +T2, +T3, +T4](
  _1: Parser[T1], _2: Parser[T2], _3: Parser[T3], _4: Parser[T4]
) extends Product4[Parser[T1], Parser[T2], Parser[T3], Parser[T4]]
     with Product
     with Parser[(T1, T2, T3, T4)]
{
  def parse(context: ParsingContext): ParsingResult[(T1, T2, T3, T4)] = {
    val rb = context.resultBuilder

    val r1 = _1.parse(context)
    if(r1.failed) return rb.failure

    val r2 = _2.parse(context)
    if(r2.failed) return rb.failure

    val r3 = _3.parse(context)
    if(r3.failed) return rb.failure

    val r4 = _4.parse(context)
    if(r4.failed) return rb.failure

    rb.success((r1.product, r2.product, r3.product, r4.product))
  }
}

object SequenceParser4 {
  /** Implicit [[smd.parsing.SequencingHeuristic]] which can be used to combine an [[smd.parsing.SequenceParser4]]
    * and an [[smd.parsing.Parser]] into an [[smd.parsing.SequenceParser5]]. */
  implicit def sequencingHeuristic[T1, T2, T3, T4, A]: SequencingHeuristic[
    /*  left: */ SequenceParser4[T1, T2, T3, T4],
    /* right: */ Parser[A],
    /*  dest: */ SequenceParser5[T1, T2, T3, T4, A]
  ] =
    SequencingHeuristic.create((l, r) => SequenceParser5(l._1, l._2, l._3, l._4, r))
}