package smd
package parsing

import scala.{Product, Product2}

// THIS FILE IS AUTOMATICALLY GENERATED
// Generated at: 2013-09-02T00:15:10Z

/** Parses 2 expressions, providing strongly-typed results.
  * 
  * @param  _1  the 1st parser in the sequence.
  * @tparam T1  the product type of the 1st parser in the sequence.
  * @param  _2  the 2nd parser in the sequence.
  * @tparam T2  the product type of the 2nd parser in the sequence.
  */
case class SequenceParser2[+T1, +T2](
  _1: Parser[T1], _2: Parser[T2]
) extends Product2[Parser[T1], Parser[T2]]
     with Product
     with Parser[(T1, T2)]
{
  def parse(context: ParsingContext): ParsingResult[(T1, T2)] = {
    val rb = context.resultBuilder

    val r1 = _1.parse(context)
    if(r1.failed) return rb.failure

    val r2 = _2.parse(context)
    if(r2.failed) return rb.failure

    rb.success((r1.product, r2.product))
  }
}

object SequenceParser2 {
  /** Implicit [[smd.parsing.SequencingHeuristic]] which can be used to combine an [[smd.parsing.SequenceParser2]]
    * and an [[smd.parsing.Parser]] into an [[smd.parsing.SequenceParser3]]. */
  implicit def sequencingHeuristic[T1, T2, A]: SequencingHeuristic[
    /*  left: */ SequenceParser2[T1, T2],
    /* right: */ Parser[A],
    /*  dest: */ SequenceParser3[T1, T2, A]
  ] =
    SequencingHeuristic.create((l, r) => SequenceParser3(l._1, l._2, r))
}